### ISSUE TITLE
Bad conversion : milli international unit per liter

### ISSUE THREAD

**Issue by guillaumealgis** [dalito/ucumvert#24] opened 2024-09-10 17:29 UTC
Hi, I think there is a problem when converting a IU with a prefix to a Pint unit:

Input : `m[IU]/L` (from the UCUM examples list, #403)
- Expected output : `milliinternational_unit / liter`
- Actual output : `meter * international_unit / liter`

Note that `k[IU]/L` is also not converted correctly to Pint.

---------

I would be glad to help, but I'm not sure where to start since the Pint documentation says regarding prefixes that 

> [...] It is important to note that prefixed defined in this way can be used with any unit, including non-metric ones (e.g. kiloinch is valid for Pint)

So I'm not sure how `mX` is not interpreted as `milliX` 🤔

**Comment by dalito** [comment] 2024-09-10 22:25
Thanks for reporting.

This is fixed in #25. I looks like it was caused by an issue in pint for custom units. pint does not recognize the prefix if the prefix could be a valid unit like "m", "k", "M" etc. - I tested with pint 0.23 and the current 0.24.3.

If you use the interactive mode (ucumvert -i), you see how the parser interprets the input. For "mX" the parser rejects the whole string because it does not contain a valid unit after "m".

**Closed** 2024-09-10 22:26 UTC
